In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
from itertools import groupby

from utils import *
from visualize import *

raw_csv = 'data.csv'

In [2]:
data = pd.read_csv(raw_csv, skiprows=[0,1,2,3], names=(['frame'] + HEADERS)).set_index('frame')
data

,snout_x,snout_y,snout_cfd,lEar_x,lEar_y,lEar_cfd,rEar_x,rEar_y,rEar_cfd,spine1_x,...,lr_corner_cfd,l_screen_x,l_screen_y,l_screen_cfd,m_screen_x,m_screen_y,m_screen_cfd,r_screen_x,r_screen_y,r_screen_cfd
frame,,,,,,,,,,,,,,,,,,,,,
0,347.368,221.276,0.998,339.779,172.237,1.0,308.384,191.340,1.0,304.585,...,0.991,170.950,82.950,0.943,330.243,69.378,0.985,484.477,67.688,0.970
1,347.462,221.276,0.999,345.557,172.237,1.0,311.504,195.804,1.0,308.187,...,0.991,170.953,82.987,0.967,330.361,69.407,0.985,484.477,67.707,0.970
2,348.278,221.276,1.000,347.596,172.237,1.0,314.244,195.804,1.0,308.187,...,0.991,171.046,83.033,0.972,330.390,69.407,0.985,484.482,67.710,0.970
3,352.592,221.254,1.000,347.596,171.879,1.0,314.562,195.804,1.0,308.317,...,0.991,171.097,82.987,0.958,330.472,69.378,0.985,484.477,67.710,0.971
4,352.687,216.565,1.000,348.001,170.011,1.0,317.910,194.290,1.0,308.317,...,0.990,171.132,82.950,0.957,330.472,69.407,0.988,484.450,67.710,0.970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50998,171.583,209.922,1.000,190.399,170.193,1.0,156.365,172.924,1.0,170.588,...,0.991,172.053,76.012,0.943,329.659,68.152,0.987,483.787,67.724,0.977
50999,171.625,209.845,1.000,190.427,170.193,1.0,157.280,173.422,1.0,170.588,...,0.991,172.054,75.994,0.942,329.660,68.152,0.987,483.830,67.724,0.977
51000,171.657,209.652,1.000,190.427,170.193,1.0,157.971,173.422,1.0,170.568,...,0.991,172.039,76.014,0.949,329.694,68.369,0.987,483.879,67.705,0.977
51001,171.657,205.529,1.000,190.427,163.668,1.0,157.971,172.823,1.0,165.818,...,0.991,172.031,75.921,0.940,329.694,68.369,0.986,483.879,67.698,0.977
51002,171.657,189.722,0.999,190.216,151.484,1.0,157.971,171.143,1.0,159.986,...,0.991,171.521,75.916,0.977,329.694,68.369,0.986,483.879,67.683,0.977

In [33]:
headers1 = [i[:-4] for i in CCOLS for j in '1234']
headers2 = [j for i in CCOLS for j in ('#of0', 'cons', '1stQ','10thQ')]

In [34]:
values = []
for col_name in CCOLS:
    print(col_name[:-4]+'\n------')
    col = data[col_name].fillna(0)
    
    zeros = (col==0)
    nums = zeros.sum()
    consecutive = max([len(list(g)) for k, g in groupby(zeros) if k]) if nums > 0 else 0
    first = str(round(col.quantile(q=0.01), 2))
    tenth = str(round(col.quantile(q=0.10), 2))
    
    print(f"# of 0s        : {nums}")
    print(f"consecutive 0s : {consecutive}")
    print(f"1st Q          : {first}")
    print(f"10th Q         : {tenth} \n")
    values += [nums, consecutive, first, tenth]

snout
------
# of 0s        : 14
consecutive 0s : 7
1st Q          : 0.91
10th Q         : 0.98

lEar
------
# of 0s        : 0
consecutive 0s : 0
1st Q          : 0.98
10th Q         : 1.0

rEar
------
# of 0s        : 7
consecutive 0s : 6
1st Q          : 0.95
10th Q         : 1.0

spine1
------
# of 0s        : 0
consecutive 0s : 0
1st Q          : 0.96
10th Q         : 1.0

spine2
------
# of 0s        : 14
consecutive 0s : 3
1st Q          : 0.98
10th Q         : 1.0

tail1
------
# of 0s        : 97
consecutive 0s : 27
1st Q          : 0.46
10th Q         : 1.0

tail2
------
# of 0s        : 174
consecutive 0s : 61
1st Q          : 0.3
10th Q         : 0.96

tail3
------
# of 0s        : 533
consecutive 0s : 68
1st Q          : 0.0
10th Q         : 0.72

food_port
------
# of 0s        : 1
consecutive 0s : 1
1st Q          : 1.0
10th Q         : 1.0

ll_corner
------
# of 0s        : 0
consecutive 0s : 0
1st Q          : 0.99
10th Q         : 0.99

lr_corner
------
# of 0s        : 0
consecutive 0s : 0
1st Q          : 0.99
10th Q         : 0.99

l_screen
------
# of 0s        : 88
consecutive 0s : 8
1st Q          : 0.42
10th Q         : 0.94

m_screen
------
# of 0s        : 39
consecutive 0s : 7
1st Q          : 0.85
10th Q         : 0.98

r_screen
------
# of 0s        : 154
consecutive 0s : 24
1st Q          : 0.47
10th Q         : 0.93

In [35]:
pd.DataFrame(np.vstack((headers1, headers2, values)))

,0,1,2,3,4,5,6,7,8,9,...,46,47,48,49,50,51,52,53,54,55
0,snout,snout,snout,snout,lEar,lEar,lEar,lEar,rEar,rEar,...,l_screen,l_screen,m_screen,m_screen,m_screen,m_screen,r_screen,r_screen,r_screen,r_screen
1,#of0,cons,1stQ,10thQ,#of0,cons,1stQ,10thQ,#of0,cons,...,1stQ,10thQ,#of0,cons,1stQ,10thQ,#of0,cons,1stQ,10thQ
2,14,7,0.91,0.98,0,0,0.98,1.0,7,6,...,0.42,0.94,39,7,0.85,0.98,154,24,0.47,0.93